/*
 * This file is generated by jOOQ.
 */
package org.blackdread.lib.restfilter.demo.jooq.tables;


import org.blackdread.lib.restfilter.demo.converter.InstantConverter;
import org.blackdread.lib.restfilter.demo.jooq.Indexes;
import org.blackdread.lib.restfilter.demo.jooq.Keys;
import org.blackdread.lib.restfilter.demo.jooq.Public;
import org.blackdread.lib.restfilter.demo.jooq.tables.records.ChildEntityRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChildEntity extends TableImpl<ChildEntityRecord> {

    private static final long serialVersionUID = 1096248196;

    /**
     * The reference instance of <code>PUBLIC.CHILD_ENTITY</code>
     */
    public static final ChildEntity CHILD_ENTITY = new ChildEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChildEntityRecord> getRecordType() {
        return ChildEntityRecord.class;
    }

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.ID</code>.
     */
    public final TableField<ChildEntityRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.NAME</code>.
     */
    public final TableField<ChildEntityRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.CREATE_TIME</code>.
     */
    public final TableField<ChildEntityRecord, Instant> CREATE_TIME = createField("CREATE_TIME", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.precision(6).nullable(false), this, "", new InstantConverter());

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.TOTAL</code>.
     */
    public final TableField<ChildEntityRecord, BigDecimal> TOTAL = createField("TOTAL", org.jooq.impl.SQLDataType.DECIMAL(20, 5).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.COUNT</code>.
     */
    public final TableField<ChildEntityRecord, Integer> COUNT = createField("COUNT", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.LOCAL_DATE</code>.
     */
    public final TableField<ChildEntityRecord, LocalDate> LOCAL_DATE = createField("LOCAL_DATE", org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.A_SHORT</code>.
     */
    public final TableField<ChildEntityRecord, Short> A_SHORT = createField("A_SHORT", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.ACTIVE</code>.
     */
    public final TableField<ChildEntityRecord, Boolean> ACTIVE = createField("ACTIVE", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.UUID</code>.
     */
    public final TableField<ChildEntityRecord, UUID> UUID = createField("UUID", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.DURATION</code>.
     */
    public final TableField<ChildEntityRecord, String> DURATION = createField("DURATION", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CHILD_ENTITY.PARENT_ID</code>.
     */
    public final TableField<ChildEntityRecord, Long> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>PUBLIC.CHILD_ENTITY</code> table reference
     */
    public ChildEntity() {
        this(DSL.name("CHILD_ENTITY"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CHILD_ENTITY</code> table reference
     */
    public ChildEntity(String alias) {
        this(DSL.name(alias), CHILD_ENTITY);
    }

    /**
     * Create an aliased <code>PUBLIC.CHILD_ENTITY</code> table reference
     */
    public ChildEntity(Name alias) {
        this(alias, CHILD_ENTITY);
    }

    private ChildEntity(Name alias, Table<ChildEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChildEntity(Name alias, Table<ChildEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ChildEntity(Table<O> child, ForeignKey<O, ChildEntityRecord> key) {
        super(child, key, CHILD_ENTITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChildEntityRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChildEntityRecord>> getKeys() {
        return Arrays.<UniqueKey<ChildEntityRecord>>asList(Keys.CONSTRAINT_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChildEntity as(String alias) {
        return new ChildEntity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChildEntity as(Name alias) {
        return new ChildEntity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChildEntity rename(String name) {
        return new ChildEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChildEntity rename(Name name) {
        return new ChildEntity(name, null);
    }
}
