/*
 * This file is generated by jOOQ.
 */
package org.blackdread.lib.restfilter.demo.jooq;


import org.blackdread.lib.restfilter.demo.jooq.tables.ChildEntity;
import org.blackdread.lib.restfilter.demo.jooq.tables.ParentEntity;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CHILD_ENTITY</code>.
     */
    public static final ChildEntity CHILD_ENTITY = ChildEntity.CHILD_ENTITY;

    /**
     * The table <code>PUBLIC.PARENT_ENTITY</code>.
     */
    public static final ParentEntity PARENT_ENTITY = ParentEntity.PARENT_ENTITY;
}
